### ISSUE TITLE
Problem with popups

### ISSUE THREAD

**Issue by brucejohnson** [0x4a616e/NSMenuFX#9]
I've changed my application to use the new (3.0.1) version of NSMenuFx.  Now when I create a PopupWindow I get this UnsatisfiedLinkError (stack trace below).  The only difference is switching to the new NSMenuFx.  If I revert to the older version (2.x) it goes away.

I haven't done any testing other than rearrange my code a little and then I get an error with a different popup that is created first.  I'll try to create a small test app, but I thought I'd post this first in case anyone has an idea what is happening.

I'm using JDK 11.0.9.1 and JavaFX 15

Caused by: java.lang.UnsatisfiedLinkError: 'void com.sun.glass.ui.mac.MacTimer._resume(long)'
	at com.sun.glass.ui.mac.MacTimer._resume(Native Method)
	at com.sun.glass.ui.Timer.resume(Timer.java:153)
	at com.sun.javafx.tk.quantum.QuantumToolkit.resumeTimer(QuantumToolkit.java:513)
	at com.sun.javafx.tk.quantum.QuantumToolkit$PulseTask.set(QuantumToolkit.java:204)
	at com.sun.javafx.tk.quantum.QuantumToolkit.requestNextPulse(QuantumToolkit.java:890)
	at javafx.scene.Parent.markDirtyLayout(Parent.java:939)
	at javafx.scene.Parent.requestLayout(Parent.java:963)
	at javafx.scene.Scene$8.invalidated(Scene.java:1228)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at javafx.scene.Scene.setRoot(Scene.java:1178)
	at javafx.scene.Scene.<init>(Scene.java:356)
	at javafx.scene.Scene.<init>(Scene.java:207)
	at javafx.scene.Scene$2$1.<init>(Scene.java:434)
	at javafx.scene.Scene$2.createPopupScene(Scene.java:434)
	at com.sun.javafx.scene.SceneHelper.createPopupScene(SceneHelper.java:99)
	at javafx.stage.PopupWindow.<init>(PopupWindow.java:158)
	at javafx.scene.control.PopupControl.<init>(PopupControl.java:115)
	at javafx.scene.control.ContextMenu.<init>(ContextMenu.java:144)

**Comment by 0x4a616e** [comment]
Hi @brucejohnson, thank you for your report. That is odd, because the stacktrace does not seem to have anything to do with NSMenuFX, so i'm wondering why you're seeing this after changing the version. Especially since NSMenuFX 3+ does not have any dependencies to `com.sun.glass.ui` anymore. 
I created a small example showing a popup menu using JavaFX15 and JDK11 and it worked without any issues.

**Comment by 0x4a616e** [comment]
Here is what I did: https://gist.github.com/0x4a616e/e3074e492c42012e0447fbbb6563cc50

**Comment by brucejohnson** [comment]
Yes, it is very strange, and I assume I'm doing something wrong somewhere in my code that for some reason is only appearing when I make this change.  I'll keep on testing till I can figure it out.
And thanks for the quick test!!

**Comment by brucejohnson** [comment]
I find that if I leave my code unchanged (using the older 2.1.7 version of nsmenufx), but just add the jar file from the new version to the classpath I get the above error.
I see that the jar file has the following dylibs:
 62860 Thu Sep 13 14:47:28 EDT 2018 libdecora_sse.dylib
364636 Thu Sep 13 14:47:28 EDT 2018 libglass.dylib
 39432 Thu Sep 13 14:47:28 EDT 2018 libjavafx_font.dylib
271552 Thu Sep 13 14:47:28 EDT 2018 libjavafx_iio.dylib
 51100 Thu Sep 13 14:47:28 EDT 2018 libprism_common.dylib
 45340 Thu Sep 13 14:47:28 EDT 2018 libprism_es2.dylib
 63992 Thu Sep 13 14:47:28 EDT 2018 libprism_sw.dylib

Is it possible that including those is creating the problem?  I assume they are necessary for nsmenufx to work??

**Comment by brucejohnson** [comment]
Removing all the dylib files from the jar file allows my application to run with the new (3.0.1) NSMenuFx.

**Comment by 0x4a616e** [comment]
Thanks for the update! You're right, those libs are not needed there at all. I fixed the `pom.xml` and published a new release `3.0.2`. It'd be great if you could give it a try and let me know if this solved the issue!

**Comment by brucejohnson** [comment]
That fixed it.  Thanks!
